<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Project::truncate();

        $projects = [
            [
                'title' => 'Tech Café',
                'slug' => 'tech-cafe',
                'category' => 'laravel stack',
                'image' => 'project-images/techcafe.webp',
                'objective' => "Scalable API development with Laravel\nSecure authentication & role-based authorization\nQR-based event workflows\nOptimized database queries for live usage\nEvent-driven backend architecture\nReact.js component-based frontend",
                'technical_highlights' => "Tech Café is a subscription-ready event management SaaS platform designed to streamline attendee engagement, station management, and real-time event tracking. The system was built as a custom web application with a modular full-stack architecture, supporting Admin, Moderator, and Attendee roles. The platform leverages backend API development, role-based authentication, and custom dashboard development to manage complex event workflows. QR-based interactions allow attendees to check in at stations instantly, while moderators and admins monitor activity through real-time dashboards. Built for performance and scalability, the system supports enterprise-level operations and high concurrent usage during live events.",
                'architecture_highlights' => "QR Code System for attendee → station and moderator → attendee actions\nLaravel API backend with events, jobs, and optimized DB queries\nReact.js frontend with fully responsive UI\nReal-time system architecture\nOptimized for high-traffic events",
                'challenges' => "Complex UI Conversion: Converted detailed Figma designs into a fully responsive React-based interface without performance degradation.\n\nQR System Conflicts: Resolved package conflicts by implementing a stable HTML5-based QR solution for consistent scanning.\n\nTight Delivery Timeline: Delivered a complete SaaS system under strict deadlines while maintaining stability and scalability.",
                'outcome' => "Delivered a production-ready event management SaaS platform\nEnabled real-time QR-based tracking for live events\nImproved operational efficiency through automated dashboards\nSupported high-traffic usage with stable backend performance\nPraised by clients for speed, reliability, and scalability\nDesigned for future expansion as an enterprise SaaS solution",
                'featured' => true,
            ],
            [
                'title' => 'Online Car Booking Platform',
                'slug' => 'online-car-booking-platform',
                'category' => 'laravel stack',
                'image' => 'project-images/car-booking.webp',
                'objective' => "The Online Car Booking Platform is a custom web application designed to simplify ride booking through real-time location selection and automated fare calculation. Built with a Laravel-based backend architecture, the system calculates ride charges dynamically based on distance, pricing rules, and configurable rate logic. Google Maps API integration enables accurate pickup and drop-off selection, distance estimation, and route optimization. The application follows enterprise web application principles, ensuring scalability, performance, and clean separation between frontend and backend. The solution is optimized for both desktop and mobile users, making it suitable for businesses looking to launch or scale a ride-booking or transportation platform.",
                'technical_highlights' => "Ride Booking & Location Selection: Users can book rides by selecting pickup and drop-off locations through an interactive Google Maps interface, delivering a seamless full stack web application experience.\n\nDynamic Pricing Engine: A backend-driven pricing algorithm calculates fares based on real-time distance, base rates, per-kilometer pricing, and configurable conditions, ensuring a production-ready scalable system.\n\nLaravel Backend API Architecture: The system is powered by backend API development using Laravel, providing secure booking management, pricing logic, and database operations.\n\nResponsive Frontend Interface: A mobile-friendly interface built with HTML, CSS, and Bootstrap ensures smooth booking flows across devices, supporting custom web application usability standards.\n\nSecure & Scalable Data Handling: The application uses structured database design and optimized queries to support growth, aligning with enterprise web application requirements.",
                'architecture_highlights' => "Frontend: HTML, CSS, Bootstrap\nBackend: PHP, Laravel\nDatabase: MySQL\nMaps & Distance Calculation: Google Maps API\nDeployment: Apache Server",
                'challenges' => "Accurate Distance & Fare Calculation: Solved by integrating Google Maps API for real-time distance and route estimation, ensuring fair and accurate pricing.\n\nScalable Pricing Logic: Implemented a flexible pricing algorithm that supports base fare, per-distance rates, and future pricing extensions.\n\nFrontend Performance Optimization: Optimized UI interactions and booking forms to ensure fast load times and smooth user experience across devices.",
                'outcome' => "Delivered a production-ready ride booking platform\nEnabled accurate, real-time fare calculation using Google Maps\nImproved user experience with a simple, mobile-friendly booking flow\nBuilt a scalable backend architecture ready for future SaaS expansion\nSuccessfully met client requirements for performance, reliability, and usability",
                'featured' => true,
            ],
            [
                'title' => 'Yoga Management Application',
                'slug' => 'yoga-management-application',
                'category' => 'laravel stack',
                'image' => 'project-images/yoga.webp',
                'objective' => "This project involved building a custom SaaS-style Yoga Management Application to help yoga studios streamline daily operations and improve client engagement. As a Full Stack Developer, I designed and implemented the complete solution with a strong focus on backend architecture, API integrations, and scalable system design. The platform centralizes instructor management, client bookings, virtual classes, and automated communication into a single enterprise-ready web application.",
                'technical_highlights' => "Virtual Class Management (Zoom API Integration): Integrated Zoom API to enable live virtual yoga sessions. Instructors can schedule, host, and manage online classes directly from the dashboard.\n\nAutomated Notifications & Communication (SMS API): Implemented SMS notifications for booking confirmations, reminders, and cancellations using Twilio SMS API.\n\nInstructor & Client Management (Custom Dashboards): Built custom dashboards for managing instructors and client profiles with full CRUD functionality and attendance tracking.\n\nAppointment Booking & Scheduling System: Developed a secure booking system with real-time availability tracking and backend validation.\n\nResponsive UI & Performance Optimization: Designed a modern, responsive interface compatible with all devices.",
                'architecture_highlights' => "Frontend: HTML, CSS, JavaScript, React\nBackend: PHP Laravel\nDatabase: MySQL\nAPIs: Zoom API, Twilio SMS API\nArchitecture: Role-Based Access Control, REST APIs, SaaS-ready backend",
                'challenges' => "API Rate Limits & Reliability: Implemented caching, batch processing, and webhook-based event handling to optimize third-party API usage.\n\nSecure & Scalable Booking Logic: Applied role-based authorization, backend validation, and transactional workflows to maintain data integrity.\n\nPerformance Optimization: Optimized backend queries and frontend rendering to deliver faster load times.",
                'outcome' => "Streamlined yoga studio operations by automating bookings and communication\nEnabled seamless virtual classes, increasing online participation\nReduced appointment no-shows through automated SMS reminders\nImproved user experience with intuitive dashboards and scheduling\nDelivered a scalable SaaS foundation ready for future feature expansion",
                'featured' => true,
            ],
            [
                'title' => 'Online Learning SaaS Platform',
                'slug' => 'online-learning-saas-platform',
                'category' => 'laravel stack',
                'image' => 'project-images/online-learning.webp',
                'objective' => "This project is a fully scalable Online Learning SaaS Platform developed using Laravel, designed to deliver virtual classrooms, teacher–student bookings, secure online payments, and Zoom-based mentorship sessions. The platform follows a full stack web application architecture with a multi-role system (Admin, Teacher, Student), real-time communication, automated scheduling, and a responsive frontend converted directly from Figma designs. The primary objective was to build a high-performance, globally accessible SaaS platform, optimized for speed, reliability, and seamless user experience across regions.",
                'technical_highlights' => "Multi-Role User System (RBAC Architecture): Admin, Teacher, and Student dashboards with specific functionalities and centralized control.\n\nZoom Integration (Video Conferencing API): End-to-end Zoom meeting lifecycle management with automatic global time-zone conversion.\n\nReal-Time Chat System: Live teacher–student messaging using WebSockets / Laravel Echo.\n\nMulti-Payment Integration (Stripe + Paymob): Secure checkout flows for international and regional payments.\n\nPixel-Perfect Figma → Frontend Conversion: Complete frontend rebuilt from scratch using Laravel Breeze with fully responsive, mobile-first UI.",
                'architecture_highlights' => "Backend: Laravel 12, PHP\nFrontend: Blade, Tailwind / Bootstrap (custom)\nDatabase: MySQL\nAuthentication: Laravel Breeze\nPayments: Stripe, Paymob\nVideo Conferencing: Zoom API\nReal-Time: Laravel Echo, Pusher, WebSockets",
                'challenges' => "Global Time Zone Scheduling: Built a dynamic time-zone engine with automated conversion + custom rescheduling system.\n\nComplex Payment Integrations: Created secure, validated payment flows and fallback mechanisms for Stripe and Paymob.\n\nAdvanced Figma Conversion: Rebuilt UI from scratch using Laravel Breeze with custom components and reusable layout system.",
                'outcome' => "The final platform is a fully scalable and production-ready SaaS capable of handling global Zoom scheduling, secure multi-payment flows, and real-time teacher–student communication. This platform significantly improved the client's operational efficiency, supported hundreds of users, and delivered a smooth, modern, and reliable remote learning experience.",
                'featured' => true,
            ],
            [
                'title' => 'PDFTools.net',
                'slug' => 'pdftools-net',
                'category' => 'laravel stack',
                'image' => 'project-images/pdftools.webp',
                'objective' => "PDFTools.net is a production-ready, scalable document management platform designed to simplify PDF and document handling for users across all devices. Built as a full stack web application using React and Laravel, the platform enables fast, accurate file conversions and document utilities without requiring sign-ups or installations. The goal was to deliver a high-performance SaaS-style system focused on speed, usability, security, and accessibility.",
                'technical_highlights' => "Document Conversion & Management Tools: PDF to Word, Compress PDF, Merge PDF, PDF to JPG, and Summarize PDF tools optimized for low latency.\n\nFile Upload & Storage Integrations: QR Code Scan Upload, Google Drive, and Dropbox integrations with secure temporary file handling.\n\nResponsive Frontend & UX: Fully responsive UI built with React, optimized for all devices with one-click actions.\n\nLocalization & Accessibility: Multi-language support and language-based UI rendering for global users.",
                'architecture_highlights' => "Frontend: React (Component-Based Architecture)\nBackend: Laravel (PHP)\nIntegrations: Google Drive API, Dropbox API, QR Code Scanner\nArchitecture: Full Stack SaaS Development\nDeployment: Production-ready scalable system",
                'challenges' => "Security & Reliability: No user data retention; files auto-delete after one hour. No watermarks or hidden limitations. Unlimited usage with consistent performance. Secure backend validation and isolated processing environment.",
                'outcome' => "Improved user experience through fast, frictionless document processing. Reduced dependency on paid or desktop-based tools. Enabled users to handle documents without technical knowledge. Delivered a custom web application capable of handling high traffic and repeated usage.",
                'featured' => true,
            ],
            [
                'title' => 'Reverse Image Search AI',
                'slug' => 'reverse-image-search-ai',
                'category' => 'laravel stack',
                'image' => 'project-images/reverse-image.webp',
                'objective' => "This full stack web application delivers scalable reverse image search functionality, enabling users to upload images and retrieve accurate matches via advanced algorithms and API integrations. As a Full Stack Web Developer, key contributions included converting Figma designs to responsive frontend and building a robust Laravel backend with image processing for production-ready performance.",
                'technical_highlights' => "Figma to Responsive Frontend: Converted UI/UX designs into HTML, CSS, Bootstrap for modern, intuitive navigation.\n\nLaravel Backend & Search Algorithm: Implemented efficient reverse image upload, processing, and MySQL database matching.\n\nAPI Integrations: Leveraged open-source Google/Bing/Yandex for enhanced accuracy and speed.\n\nScalable Architecture: Supported multiple formats with metadata storage for future SaaS expansions.",
                'architecture_highlights' => "Frontend: HTML, CSS, Bootstrap\nBackend: PHP, Laravel\nDatabase: MySQL\nImage Processing: Open source google, bing, yandex APIs.\nHosting & Deployment: Apache Server",
                'challenges' => "Accurate Matching at Scale: Clients needed fast, accurate matching without performance lags. Developed custom image similarity algorithms using Google, Bing, and Yandex APIs.\n\nFrontend Performance Optimization: Optimized frontend by minifying CSS/JS files, reducing load times by 40% while ensuring responsiveness.",
                'outcome' => "Delivered a production-ready reverse image search platform. Enabled fast, accurate matching using multiple search engines. Optimized for high traffic and performance across all devices.",
                'featured' => true,
            ],
            [
                'title' => 'Yohov - Travel Booking Platform',
                'slug' => 'yohov-travel-booking',
                'category' => 'mern stack',
                'image' => 'project-images/yovho.webp',
                'objective' => "Yohov is a scalable full-stack SaaS travel booking platform designed for seamless global travel planning. It provides real-time booking, secure payments, guest reviews, and host dashboards.",
                'technical_highlights' => "Real-Time Booking & Availability\nSecure Payment & Transactions via Stripe\nGuest Reviews & Ratings\nHost & Property Management Dashboard\nMobile & Cross-Platform Access\nSEO-Optimized Travel Blogs",
                'architecture_highlights' => "Frontend: React.js, Next.js\nBackend: Node.js, Nest.js\nDatabase: MongoDB\nPayment: Stripe\nTools: REST APIs, Caching, React Native-ready",
                'challenges' => "Real-time synchronization across global locations and preventing double-bookings through optimized backend logic and caching.",
                'outcome' => "Delivered a scalable full-stack platform with enterprise-level features. Enabled real-time bookings and dynamic pricing globally.",
                'featured' => true,
            ],
            [
                'title' => 'HouseHub365 - Home Maintenance',
                'slug' => 'househub365-home-maintenance',
                'category' => 'mern stack',
                'image' => 'project-images/househub.webp',
                'objective' => "HouseHub365 is a full-stack SaaS home maintenance management platform designed to simplify property care for homeowners by automating alerts and contractor coordination.",
                'technical_highlights' => "Room-Wise Appliance Tracking\nAutomated Maintenance Alerts\nCentralized Service History Dashboard\nSmart Scheduling & Contractor Management\nResponsive, User-Friendly Interface\nScalable Cloud-Ready Backend",
                'architecture_highlights' => "Frontend: React.js, Next.js, Tailwind CSS\nBackend: Node.js, Express.js\nDatabase: MongoDB\nDeployment: AWS / Azure compatible",
                'challenges' => "Coordinating multiple service schedules and contractor availability in real-time while maintaining a simple user interface for homeowners.",
                'outcome' => "Provides homeowners with a centralized solution to manage appliances and services. Saves time and prevents breakdowns through automated workflows.",
                'featured' => true,
            ],
            [
                'title' => 'iDurar ERP',
                'slug' => 'idurar-erp',
                'category' => 'mern stack',
                'image' => 'project-images/idurar.webp',
                'objective' => "iDurar ERP is an all-in-one business management platform designed to centralize operations including HR, CRM, finance, and inventory for growing businesses.",
                'technical_highlights' => "Employee & Customer Management (CRM)\nAutomated Financial Operations (Invoicing, Stripe/PayPal)\nInventory & Resource Tracking with alerts\nAnalytics & Real-time Reporting Dashboards\nRole-Based Access Control (RBAC)",
                'architecture_highlights' => "Frontend: React.js (TypeScript)\nBackend: Node.js, NestJS\nDatabase: MongoDB\nPayments: Stripe, PayPal\nDeployment: Cloud-ready (AWS/Azure)",
                'challenges' => "Integrating disparate business processes into a single unified system with secure, role-based visibility and real-time data accuracy.",
                'outcome' => "Reduces operational overhead significantly and improves reporting speed. Provides a secure and scalable foundation for business growth.",
                'featured' => true,
            ],
            [
                'title' => 'ScholarAI - Academic Search',
                'slug' => 'scholarai-academic-search',
                'category' => 'ai powered',
                'image' => 'project-images/ifocus.webp',
                'objective' => "ScholarAI is an AI-powered academic search platform that combines scalable backend architecture with advanced search and AI-powered summarization for research papers.",
                'technical_highlights' => "Advanced Search & Filtering (Node.js APIs)\nAI-Powered Article Summaries\nReal-Time AI Chat for Academic Queries\nData Management & Metadata Handling\nScalable, Production-Ready Architecture",
                'architecture_highlights' => "Frontend: React.js\nBackend: Node.js, Express.js\nDatabase: MongoDB / PostgreSQL\nAI: Custom Summarization APIs, Caching layers",
                'challenges' => "Processing and indexing large volumes of research papers while maintaining fast retrieval times and accurate AI-generated insights.",
                'outcome' => "Delivers a scalable system capable of processing thousands of research papers efficiently. Bridges traditional search with AI-powered insights.",
                'featured' => true,
            ],
            [
                'title' => 'Rewordify - AI Rewriting',
                'slug' => 'rewordify-ai-rewriting',
                'category' => 'ai powered',
                'image' => 'project-images/rewordify.webp',
                'objective' => "Rewordify is a scalable AI-powered content rewriting platform engineered to handle high-volume text processing, document uploads, and AI-driven generation.",
                'technical_highlights' => "AI-Powered Content Processing Backend\nConfigurable API Parameters (Tone, Style, Length)\nDocument Upload System (PDF, Word, Text)\nPersistent Content Storage & Export Services\nAdmin & Support Module with RBAC",
                'architecture_highlights' => "Backend: Node.js, Express.js\nDatabase: MongoDB\nFrontend: React.js\nAI: Modular API layer for future extensibility",
                'challenges' => "Handling concurrent AI requests for large document processing without latency while ensuring secure content storage and export functionality.",
                'outcome' => "Efficiently processes content rewriting requests through secure and optimized APIs. Saves time for users while ensuring scalable processing.",
                'featured' => true,
            ],
            [
                'title' => 'SEOHub - SEO Automation',
                'slug' => 'seohub-seo-automation',
                'category' => 'ai powered',
                'image' => 'project-images/seohub.webp',
                'objective' => "SEOHub automates keyword research and page generation based on business inputs, organizing data by sector, discipline, and location for precision.",
                'technical_highlights' => "AI-Powered Keyword & Page Generation\nStructured Data Organization & Filtering\nComprehensive Admin Panel for Sector Management\nRecord Keeping & Analytics Audit Trails\nExport options for reporting",
                'architecture_highlights' => "Frontend: React.js\nBackend: Node.js / Express.js\nDatabase: MongoDB / SQL\nTools: Excel export libraries, SEO APIs",
                'challenges' => "Automating complex SEO workflows and ensuring high relevance in keyword generation across diverse business sectors.",
                'outcome' => "Reduces manual SEO effort while improving organization and efficiency. Enables businesses to manage campaigns more effectively at scale.",
                'featured' => true,
            ],
            [
                'title' => 'TrafikBilder - Traffic Media SaaS',
                'slug' => 'trafikbilder-media-saas',
                'category' => 'mern stack',
                'image' => 'project-images/trafikbilder.webp',
                'objective' => "TrafikBilder is a subscription-based SaaS platform providing access to traffic-related images and videos through a scalable full-stack web application.",
                'technical_highlights' => "Tiered User Access & Subscriptions\nProfile & Content Management for registered users\nCloud Media Storage & Scalability\nRobust Administrative Controls & Verification\nMedia Data Export for reporting",
                'architecture_highlights' => "Frontend: React.js\nBackend: Node.js / Express.js\nDatabase: MongoDB\nStorage: Cloud-based (AWS S3 / Firebase)\nFeatures: Subscriptions, Search Filters",
                'challenges' => "Managing high-volume media storage and ensuring fast delivery to both free and premium users with secure access control.",
                'outcome' => "Successfully provides a centralized platform for traffic media with scalable cloud storage and administrative oversight.",
                'featured' => true,
            ],
            [
                'title' => 'Big Star - Vehicle Marketplace',
                'slug' => 'big-star-marketplace',
                'category' => 'mern stack',
                'image' => 'project-images/bigstar.webp',
                'objective' => "Big Star is a vehicle marketplace platform designed to streamline buying and selling cars, trucks, and bikes through advanced search and direct communication.",
                'technical_highlights' => "Advanced Search & Dynamic Filtering\nDetailed Vehicle Listings with Specifications\nDirect Communication via WhatsApp Integration\nSpare Parts Browsing Ecosystem\nAdministrative Sales Monitoring & Reporting",
                'architecture_highlights' => "Tech: MERN Stack (MongoDB, Express, React, Node)\nFeatures: Multi-language support, Grid/List views, WhatsApp integration",
                'challenges' => "Creating a seamless communication channel between buyers and sellers while maintaining structured vehicle data and listing quality.",
                'outcome' => "Delivers a comprehensive marketplace solution with full operational visibility for administrators and an intuitive user experience.",
                'featured' => true,
            ],
            [
                'title' => 'Diamond Galaxy - MLM Platform',
                'slug' => 'diamond-galaxy-mlm',
                'category' => 'mern stack',
                'image' => 'project-images/daimondgalaxy.webp',
                'objective' => "Diamond Galaxy is a multi-level marketing (MLM) platform that facilitates structured earnings through task completion and referral-based commissions.",
                'technical_highlights' => "Account Activation via Payment\nTask-Based Earning Mechanism\nReferral Commission & MLM Structure\nSlot-Based Positioning System\nGamified Leveling & Rewards System\nCentralized Admin Compliance Controls",
                'architecture_highlights' => "Frontend: React.js\nBackend: Node.js, Express.js\nDatabase: MongoDB\nAuth: JWT & Role-Based Access Control",
                'challenges' => "Ensuring operational fairness and transparency in a complex MLM structure while maintaining secure transaction flows and task verification.",
                'outcome' => "Provides a robust and engaging MLM solution designed for growth and operational efficiency with dynamic administrative controls.",
                'featured' => true,
            ],
            [
                'title' => 'GENX - AI Career Co-pilot',
                'slug' => 'genx-ai-career',
                'category' => 'ai powered',
                'image' => 'project-images/genx.webp',
                'objective' => "GENX is an AI career guidance and job-matching platform that aggregates listings from multiple sources and uses semantic search for accurate matching.",
                'technical_highlights' => "AI Job Aggregation & Data Normalization\nSemantic CV-to-Job Matching (OpenAI Embeddings)\nAI Resume Builder & Career Insights\nCustom Admin Performance Dashboards\nVector-Based Semantic Search",
                'architecture_highlights' => "Backend: PHP, Laravel, Queue Workers\nAI: OpenAI, Gemini API, Semantic Search\nDatabase: MySQL with Query Optimization",
                'challenges' => "Standardizing inconsistent job data from multiple APIs and improving matching accuracy beyond simple keyword filters.",
                'outcome' => "Delivered a production-ready AI SaaS platform for job discovery, helping users navigate the market with intelligent automation.",
                'featured' => true,
            ],
            [
                'title' => 'Zorova - Service Marketplace',
                'slug' => 'zorova-marketplace',
                'category' => 'mern stack',
                'image' => 'project-images/zorova.webp',
                'objective' => "Zorova is an on-demand service marketplace for massage, fitness, and more, using location-based allocation to dispatch professionals efficiently.",
                'technical_highlights' => "Geo-Based Dispatch & Location Matching\nMulti-Service Management (Massage, Fitness, SOS)\nFranchise, Referral & Membership Modules\nReal-Time Service Tracking & Monitoring\nSecure Payment Gateway Integration",
                'architecture_highlights' => "Frontend: React.js\nBackend: Node.js, Express.js\nDatabase: MongoDB\nAuth: JWT & RBAC\nArchitecture: Full Stack SaaS Development",
                'challenges' => "Dynamically assigning professionals based on proximity and availability while ensuring service quality and transaction security.",
                'outcome' => "Streamlines end-to-end service management from booking to revenue tracking with a production-ready scalable platform.",
                'featured' => true,
            ],
            [
                'title' => 'Smart Transform AI',
                'slug' => 'smart-transform-ai',
                'category' => 'ai powered',
                'image' => 'project-images/Smart Transform ai_20251201_221716_0000.jpg.jpeg',
                'objective' => "Smart Transform AI is a full-stack platform that integrates multiple AI models to automate content creation across text, image, audio, and video formats.",
                'technical_highlights' => "AI Model Orchestration (OpenAI, Gemini, Whisper)\nMulti-Modal Generation (Text-to-Video, Text-to-Image, etc.)\nCustom Usage Dashboards & Analytics\nSecure API Key & Quota Management\nQueue-Based Processing Engine",
                'architecture_highlights' => "Frontend: Next.js, Tailwind CSS\nBackend: Modular API Orchestration\nAI: OpenAI, Gemini, Whisper, Vision models\nArchitecture: High-performance async processing",
                'challenges' => "Combining diverse AI tools without latency and ensuring high accuracy across OCR, ASR, and generative workflows.",
                'outcome' => "Delivered a production-ready AI SaaS platform capable of handling complex content pipelines with enterprise-grade monitoring.",
                'featured' => true,
            ],
            [
                'title' => 'TravelSphere - Community Blog',
                'slug' => 'travelsphere-community',
                'category' => 'mern stack',
                'image' => 'project-images/tripvista.webp',
                'objective' => "TravelSphere is a responsive travel blog and community-driven content platform developed to promote cultural awareness and sustainable tourism.",
                'technical_highlights' => "Dynamic Blog & Content Management System\nCommunity Engagement (Comments, Reviews)\nUser-Generated Content Uploads\nIntegrated Image Gallery & Cloud Storage\nTier-Based Subscription & Premium Model",
                'architecture_highlights' => "Stack: MERN (MongoDB, Express, React, Node)\nCloud: Secure cloud media storage\nAuth: Role-based authentication\nFeatures: SEO-optimized architecture, lazy loading",
                'challenges' => "Maintaining high performance with media-heavy content and handling concurrent uploads from a growing community of travelers.",
                'outcome' => "Successfully delivers a scalable, interactive platform that fostering community engagement and sustainable tourism exploration.",
                'featured' => true,
            ],

        ];

        foreach ($projects as $project) {
            Project::create($project);
        }
    }
}
